### ISSUE TITLE
How to search extattrs

### ISSUE THREAD

**Issue by zimage** [dnaeon/pyinfoblox#6]
I'm trying to perform a case insensitive search based on an extensible attribute. Infoblox API documentation tells me to prepend an asterisk to the the name when searching and to use ':=' instead of '=' in the query string. There doesn't seem to be any way to do this.

**Comment by jamesarmitage** [comment]
I think you need to use ':~=' (note the tilde).

Check here: https://ipam.illinois.edu/wapidoc/index.html#get

Scroll down to "Search Modifiers" for the reference table.

**Comment by dnaeon** [comment]
Using the `infoblox.network.get(extattrs='*Site:="123"')` throws an error because it basically contains the extensible attributes associated with an object.

Searching of objects with extensible attributes however requires the use of a special syntax.

>## Extensible attributes search
>Extensible attributes require a special search syntax. Searches for extensible attributes are sent by prefixing the extensible attribute name with an asterisk (*). Standard search suffixes can be applied to the extensible attribute if they are supported by the attribute type.

>For example, a search for all networks that contain a string extensible attribute named ‘Building’ with a case-insensitive value ‘data center’ should be sent to the server as follows (using HTTP GET):

> GET /wapi/v2.1/network?*Building:='Data Center'

That means that we need to use a bit different syntax as well when searching for objects with given extensible attributes.

Searching for object using case-sensitivity:

```python
>>> params = {"*Building": "Data Center"}
>>> infoblox.network.get(**params)
```

Doing the same but this time using case-insensitive search

```python
>>> params = {"*Building:": "Data Center"}
>>> infoblox.network.get(**params)
```

In the above snippets `infoblox` is already and instantiated `pyinfoblox.InfobloxWAPI` object.

Note also that in the second example for case-insensitive search I'm adding a colon `:` right after the extensible attribute name, which will be resolved as `Building:='Data Center'` when sending the request to Infoblox.

You may also want to check https://github.com/dnaeon/pyinfoblox/issues/2 other examples on extensible attributes.

Hope that helps.
